services:
  pipeline:
    build:
      context: .
      dockerfile: pipeline/Dockerfile
    env_file: .env
    environment:
      PYTHONPATH: /app/pipeline
    volumes:
      - .:/app
    working_dir: /app
